{% set name = "parcels" %}
{% set version = "2.2.0" %}
{% set sha256 = "50e9ce50b598ae7b6ff1e3c7b71d18ca0e05ae4470d5ebc8e7ca93290cee2ed1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/oceanparcels/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - {{ PYTHON }} setup.py bdist_wheel --dist-dir=dist
    - {{ PYTHON }} -m pip install --find-links=dist --no-deps --ignore-installed --no-cache-dir -vvv {{ name }}
  entry_points:
    - parcels_get_examples = parcels.scripts.get_examples:main

requirements:
  build:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - wheel
  run:
    - python
    - cachetools >=1.0.0
    - cftime
    - cgen
    - dask
    - enum34  # [py2k]
    - gcc_linux-64  # [linux]
    - clang_osx-64  # [osx]
    - m2w64-toolchain  # [win]
    - matplotlib-base >=2.0.2
    - netcdf4 >=1.1.9
    - numpy >=1.9  # [linux64 or osx]
    - numpy >=1.11  # [win]
    - progressbar2
    - pymbolic
    - python-dateutil
    - scipy >=0.16.0
    - six >=1.10.0
    - xarray >=0.10.8

test:
  imports:
    - parcels
    - parcels.scripts
    - parcels.kernels
    - parcels.tools
  commands:
    - parcels_get_examples parcels_examples

about:
  home: http://github.com/OceanParcels/parcels
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Probably A Really Computationally Efficient Lagrangian Simulator

  description: |
    Parcels (Probably A Really Computationally Efficient Lagrangian Simulator)
    is a set of Python classes and methods to create customisable particle 
    tracking simulations using output from Ocean Circulation models. 
    Parcels can be used to track passive and active particulates such as 
    water, nutrients, plankton, plastic and fish.
  doc_url: http://oceanparcels.org/
  dev_url: https://github.com/OceanParcels/parcels

extra:
  recipe-maintainers:
    - erikvansebille
    - delandmeterp
    - ckehl
    - willirath
