{% set name = "parcels" %}
{% set version = "2.0.0beta2" %}
{% set sha256 = "557b282b260c496d077f479905d9f6b0d5f93f6a0606098ef596fc3ec8250a49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/oceanparcels/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - "{{ PYTHON }} setup.py bdist_wheel --dist-dir=dist"
    - "{{ PYTHON }} -m pip install --find-links=dist --no-deps --ignore-installed --no-cache-dir -vvv {{ name }}"

requirements:
  build:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - wheel
  run:
    - python
    - cachetools >=1.0.0
    - cftime
    - cgen
    - enum34  # [py2k]
    - gcc_linux-64  # [linux]
    - clang_osx-64  # [osx]
    - m2w64-toolchain  # [win]
    - matplotlib >=2.0.2
    - netcdf4 >=1.1.9,<=1.4.1
    - numpy >=1.9  # [linux64 or osx]
    - numpy >=1.16.2  # [win]
    - progressbar2
    - pymbolic
    - python-dateutil
    - scipy >=0.16.0
    - six >=1.10.0
    - xarray >=0.11.3

test:
  imports:
    - parcels
    - parcels.scripts
    - parcels.kernels
    - parcels.tools
  commands:
    - parcels_get_examples parcels_examples  # [linux or osx]

about:
  home: http://github.com/OceanParcels/parcels
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Probably A Really Computationally Efficient Lagrangian Simulator'

  description: |
    Parcels (Probably A Really Computationally Efficient Lagrangian Simulator)
    is a set of Python classes and methods to create customisable particle 
    tracking simulations using output from Ocean Circulation models. 
    Parcels can be used to track passive and active particulates such as 
    water, nutrients, plankton, plastic and fish.
  doc_url: http://oceanparcels.org/
  dev_url: https://github.com/OceanParcels/parcels

extra:
  recipe-maintainers:
    - erikvansebille
    - delandmeterp
    - willirath
