schema_version: 1

context:
  name: parcels
  version: "4.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Parcels-code/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: c6214c39202aeb0ee0858529a3a778403cb07e8190fc3e862624ec36f1d3feea

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - wheel
  run:
    - python >=${{ python_min }}
    - cf_xarray >=0.10.0
    - cftime >=1.6.3
    - dask >=2025.7.0
    - holoviews >=1.22.0 # https://github.com/prefix-dev/rattler-build/issues/2326
    - netcdf4 >=1.6.0
    - numpy >=2.2.0
    - pandas >=2.3
    - polars >=1.32.0
    - pooch >=1.8.0
    - pyarrow >=21.0.0
    - pyogrio # needed for geopandas (uxarray -> geoviews -> geopandas -> pyogrio, but for some reason conda doesn't pick it up automatically)
    - tabulate >=0.9.0
    - tqdm >=4.67.0
    - uxarray >=2026.04.1
    - xarray >=2025.8.0
    - zarr >=3.1

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - parcels
      pip_check: false # Remove line to enable `pip check`. Do when next minor (vx.this.x) of uxarray comes out (currently its resolving to `v2026.08.0` which has broken metadata https://github.com/UXARRAY/uxarray/issues/1542#issuecomment-5390203863 )

about:
  license: MIT
  license_file: LICENSE.md
  summary: Parcels - A highly customisable Lagrangian simulation framework
  description: |
    Parcels provides a set of Python classes and methods to create customisable particle tracking simulations using gridded output from geoscientific circulation models.
  homepage: https://github.com/Parcels-code/parcels
  repository: https://github.com/Parcels-code/parcels
  documentation: https://parcels-code.org/

extra:
  recipe-maintainers:
    - VeckoTheGecko
    - erikvansebille
    - willirath
