appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: e0QwGPnSImlbezdNrkG5NqUNjots5m6yC4YXXU4QlHSacsIYxJIIxgFdUtFxRTPRE4E/ALO97KzQ3Mmu/V8w+ns2YPjCuvQ3I8OCW9p1b2k4BPMsFA95iIFK5KBDESmWZCLB+A37t4LajKPiwTsIi9El/H3yxKLWHdXVAarLFDqa0IHmx3oNyUetVv37uDkw9CiczVcdHSN0TMCbocVRKohYhXdYyUwdEZg1bE7g2afqS+OxzGjexYWYWN6sGf7vxJsfrTKfMBmcwkstepO3PlRxoUmHAyJ6P2LuVuPJALW+g2wqpgm/adSSeJsD+FghvN+6UwDPtkEnPPt2SUnpz6AiKT/woCL7wWDL2+J4gkyrXp/rZpT7BSpVYWLwXrqMpR2tnH/kzPyMtupw1JSa2TNbtZuK9q7iF//oipktjRjTGazW6bG5rkqdxR1fS8KRJbzQcVhV9xsa0B80XRq8Hvy5nxzk4nH62809IwMhVslKeveo+qeuODxsYPCQrOs/lF0jdjL5WGBIRSyDTksQR8vZBg0KW0X92uGuiqGc/jDxCCiYqPF/S28jBqveqE+BnHaYOt4rR/cp5qmQGc6ZnfN+Giuz05hbmPFH1kLHpgHshdZvO6hY4TlEGtluZooraZ17CVn3GONzFpijSNoEdC1Dy21qeE9JLnHzfKzrOL4=}
